Traceback (most recent call last):
  File "/Users/mshira/Dropbox/2024数理工学実験２/2024Shiraishi/.venv/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/mshira/Dropbox/2024数理工学実験２/2024Shiraishi/.venv/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mshira/Dropbox/2024数理工学実験２/2024Shiraishi/.venv/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/mshira/Dropbox/2024数理工学実験２/2024Shiraishi/.venv/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/mshira/Dropbox/2024数理工学実験２/2024Shiraishi/.venv/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/mshira/Dropbox/2024数理工学実験２/2024Shiraishi/.venv/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#ニュートン法1（numpy配列を用いる）
import numpy as np

epsilon=10e-6 #精度の設定
n_max=10 #最大繰り返し回数の設定
x_i=np.zeros(n_max+1) #1ステップ毎のxの値
delta=np.abs(epsilon*100) # 解の精度の初期値x_(i+1)-x_(i)
x_i[0]=x_0 #初期値の設定

n=0 #カウンタ変数
while 条件の設定: #反復を行う条件の設定
    （1行目）このブロックについては自分で考える
    （2行目）このブロックについては自分で考える
    n+=1
    print("x_i[{}]={:.12}, x_i[{}]={:.16}, delta={:.12}".format(n-1, x_i[n-1], n, x_i[n], delta))
if 条件の設定: #解の精度の設定
    print("x={}".format(x_i[n]))
else:
    print("解なし")

------------------


[0;36m  Cell [0;32mIn[1], line 12[0;36m[0m
[0;31m    （1行目）このブロックについては自分で考える[0m
[0m    ^[0m
[0;31mSyntaxError[0m[0;31m:[0m invalid character '（' (U+FF08)


